
version: "2"
    services:
        data-service:
            build: .
            links:
                - db
            ports:
              - "50051:50051"
            volumes_from: ["db"]
            environment:
                DATABASE_HOST: db
        db:
            image: postgres:9.5
            environment:
                - POSTGRES_USER=ecd_user
                - POSTGRES_PASSWORD=ecd_pass
                - POSTGRES_DB=ecd_db
            ports:
              - "8000:5432"
            expose:
                - 5432
            #volumes_from:
                #- data-volume
                # - container:postgres9.5-data
            restart: always

        data-volume:
            image: busybox
            command: echo "I'm data container"
            volumes:
                - /var/lib/postgresql/data



